version: '3'
services:
  postgres:
    ports: 
    - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    image: "docker.io/library/postgres:12"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
  parser:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres
volumes:
  postgres_data:

